version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:181633351618:task-definition/bluegreen-taskdefinition:1"
        LoadBalancerInfo:
            ContainerName: "sample-app"
            ContainerPort: 80
        PlatformVersion: "LATEST"

